import type { Metadata } from "next";
import { Spline_Sans_Mono, Sofia_Sans_Condensed } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const sofiaCondensed = Sofia_Sans_Condensed({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"],
  variable: "--font-sofia-condensed",
});

const splineSans = Spline_Sans_Mono({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-spline",
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${sofiaCondensed.variable} ${splineSans.variable}`} >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
